spring:
  application:
    name: unit-test-spring
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:app.pub

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
server:
  port: 5000
